# Generated by Django 4.2.3 on 2023-07-14 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HellowWorld',
            new_name='HelloWorld',
        ),
    ]
